# A workflow that is scheduled daily and carries out maintenance tasks.
name: Maintenance

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }

permissions:
  { }

concurrency:
  group: package-repository
  cancel-in-progress: false

jobs:
  # A job to delete obsolete package versions (container images) from the GitHub registry.
  delete_container_images:
    name: Delete obsolete package versions (container images).
    runs-on: ubuntu-latest

    permissions:
      packages: write  # To be able to delete container images.

    steps:
      - name: Delete obsolete package versions.
        uses: jenskeiner/ghcr-container-repository-cleanup-action@6822ce86a1dec9d3daf33c400176a4bf5dde5fb8 # v1.3.2
        with:
          # Don't delete main, master, develop, semantic version tags, and pull request tags.
          exclude-tags: '^(?:main|master|develop|buildcache|\d+(?:\.\d+){0,2}|pr-\d+)$'
          # Do not keep any other tags.
          keep-n-tagged: 0
          # Do not keep any other images.
          keep-n-untagged: 0
          token: ${{ secrets.GITHUB_TOKEN }}
