# A workflow that is scheduled daily and carries out maintenance tasks.
name: PR Closed

on:
  pull_request:
    types: [ closed ]

permissions:
  { }

concurrency:
  group: package-repository
  cancel-in-progress: false

jobs:
  # A job to delete package versions (container images) from the GitHub registry related to the PR.
  delete_container_images:
    name: Delete PR package versions (container images).
    runs-on: ubuntu-latest

    permissions:
      packages: write  # To be able to delete container images.

    steps:
      - name: Delete PR package versions.
        uses: jenskeiner/ghcr-container-repository-cleanup-action@6822ce86a1dec9d3daf33c400176a4bf5dde5fb8 # v1.3.2
        with:
          include-tags: pr-${{github.event.pull_request.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
