name: Publish Python distributions to PyPI

on:
  release:
    types: [ published ]

permissions:
  contents: read

concurrency:
  group: publish
  cancel-in-progress: false

env:
  PACKAGE_NAME: exchange-calendar-service
  MODULE_NAME: exchange_calendar_service
  PYTHON_VERSION: "3.13"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-testpypi:
    name: Build and publish Python distributions to TestPyPI.
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write  # Required for trusted publishing.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v7
        with:
          enable-cache: false  # No cache when building RCs or releases.
      - name: Set up Python
        shell: bash
        run: uv python install ${PYTHON_VERSION}
      - name: Determine package version.
        shell: bash
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          export PACKAGE_VERSION=${REF_NAME}
          echo "Version is $PACKAGE_VERSION."
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
      - name: Build package
        run: uv build
      - name: Publish package to Test PyPI.
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
      - name: Test that the package can be installed and imported (Test PyPI).
        shell: bash
        run: |
          i=0
          max=10
          exists=0
          while [ $i -lt $max ] && [ $exists -eq 0 ]; do
              i=$(expr $i + 1)
              if curl -f -s https://test.pypi.org/pypi/${PACKAGE_NAME}/json | jq -e ".releases | has(\"${PACKAGE_VERSION}\")" &> /dev/null; then
                  echo "$i/$max Package has appeared in index."
                  exists=1
              else
                  echo "$i/$max Package has not appeared in index yet. Sleeping 5s."
                  sleep 5s
              fi
          done
          if [ $exists -ne 0 ]; then
              sleep 5s
              i=0
              max=3
              while [ $i -lt $max ]; do
                  if uv run -n --refresh --default-index https://test.pypi.org/simple --index https://pypi.org/simple --index-strategy unsafe-best-match --with "${PACKAGE_NAME}==${PACKAGE_VERSION}" --no-project -- python -c "from importlib.metadata import version;print(version(\"${MODULE_NAME}\"))"; then
                      exit 0
                  else
                      echo "The command failed. Retrying $i/$max."
                      i=$(expr $i + 1)
                      sleep 5s
                  fi
              done
              echo "The command failed $i/$max times. Failing the job."
              exit 1
          else
              echo "The package was not found in the package index. Test installation and import failed."
              exit 1
          fi
  build-and-publish-pypi:
    name: Build and publish Python distributions to PyPI.
    needs: build-and-publish-testpypi
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # Required for trusted publishing.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v7
        with:
          enable-cache: false  # No cache when building RCs or releases.
      - name: Set up Python
        shell: bash
        run: uv python install ${PYTHON_VERSION}
      - name: Determine package version.
        shell: bash
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          export PACKAGE_VERSION=${REF_NAME}
          echo "Version is $PACKAGE_VERSION."
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
      - name: Build package
        run: uv build
      - name: Publish package to PyPI.
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
      - name: Test that the package can be installed and imported (PyPI).
        shell: bash
        run: |
          i=0
          max=10
          exists=0
          while [ $i -lt $max ] && [ $exists -eq 0 ]; do
              i=$(expr $i + 1)
              if curl -f -s https://pypi.org/pypi/${PACKAGE_NAME}/json | jq -e ".releases | has(\"${PACKAGE_VERSION}\")" &> /dev/null; then
                  echo "$i/$max Package has appeared in index."
                  exists=1
              else
                  echo "$i/$max Package has not appeared in index yet. Sleeping 5s."
                  sleep 5s
              fi
          done
          if [ $exists -ne 0 ]; then
              sleep 5s
              i=0
              max=3
              while [ $i -lt $max ]; do
                  if uv run -n --refresh --default-index https://pypi.org/simple --index https://pypi.org/simple --with "${PACKAGE_NAME}==${PACKAGE_VERSION}" --no-project -- python -c "from importlib.metadata import version;print(version(\"${MODULE_NAME}\"))"; then
                      exit 0
                  else
                      echo "The command failed. Retrying $i/$max."
                      i=$(expr $i + 1)
                      sleep 5s
                  fi
              done
              echo "The command failed $i/$max times. Failing the job."
              exit 1
          else
              echo "The package was not found in the package index. Test installation and import failed."
              exit 1
          fi

  build-container-images:
    name: Build and push container images.
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # To be able to push new images to the registry.
      attestations: write  # To be able to upload attestations for new images.
      id-token: write  # To be able to mint a token to sign new attestations.

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Determine package version.
        shell: bash
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          export PACKAGE_VERSION=${REF_NAME}
          echo "Version is $PACKAGE_VERSION."
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.PACKAGE_VERSION }},suffix=
            type=semver,pattern={{major}}.{{minor}},value=${{ env.PACKAGE_VERSION }},suffix=
            type=semver,pattern={{major}},value=${{ env.PACKAGE_VERSION }},suffix=
            type=raw,value=latest
          flavor: |
            latest=false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Log in to the Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          push: true
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64, linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          provenance: mode=max
          sbom: true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
